Implemented basic water shader
StijnKlopper/FYS-X pull request #60
Opened 2021-01-12 20:35 UTC by StijnKlopper

Implemented basic water shader for ocena based on the unity standard assets:
https://assetstore.unity.com/packages/essentials/asset-packs/standard-assets-for-unity-2018-4-32351

2021-01-12 20:38 UTC, StijnKlopper commented
Video of shader in action
https://user-images.githubusercontent.com/33661926/104369914-6c57b800-551e-11eb-92f0-d6b447dd5aac.mp4

2021-01-13 09:27 UTC, appelmoesje requested changes

2021-01-13 09:27 UTC, appelmoesje commented on No FYS-X Sky/Assets/Helpers/WaterScripts/SpecularLighting.cs
> +
Remove whitespace

2021-01-13 09:27 UTC, appelmoesje commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterBase.cs
> +
Remove white whitespace

2021-01-13 09:27 UTC, appelmoesje commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterBase.cs
> +
Remove white whitespace

2021-01-13 09:27 UTC, appelmoesje commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterTile.cs
> +
Remove white whitespace

2021-01-13 09:27 UTC, appelmoesje commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterTile.cs
> +
Remove white whitespace

2021-01-13 09:31 UTC, Fakerick1 requested changes
Looks good bro

2021-01-13 09:31 UTC, Fakerick1 commented on No FYS-X Sky/Assets/Helpers/WaterScripts/MeshContainer.cs
> +namespace UnityStandardAssets.Water
We dont use namespaces in the rest of the project

2021-01-13 09:31 UTC, Fakerick1 commented on No FYS-X Sky/Assets/Helpers/WaterScripts/MeshContainer.cs
> +        public Mesh mesh;
public starts with a capital letter

2021-01-13 09:31 UTC, Fakerick1 commented on No FYS-X Sky/Assets/Helpers/WaterScripts/SpecularLighting.cs
> +        public Transform specularLight;
public starts with capital

2021-01-13 09:31 UTC, Fakerick1 commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterBase.cs
> +        public Material sharedMaterial;
public starts with capital

2021-01-13 09:31 UTC, Fakerick1 commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterBase.cs
> +        public bool edgeBlend = true;
![image](https://user-images.githubusercontent.com/8337434/104433342-4962ed80-558a-11eb-81c0-c8c1a7fd271d.png)

2021-01-13 09:31 UTC, Fakerick1 commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterTile.cs
> +
Remove white whitespace

2021-01-13 09:31 UTC, Fakerick1 commented on No FYS-X Sky/Assets/Helpers/WaterScripts/WaterTile.cs
> +
Remove white whitespace

2021-01-14 11:41 UTC, Fakerick1 approved these changes

2021-01-14 18:19 UTC, merged